### PR TITLE
Add snoop aggregator

### PR DESCRIPTION
**Pull request by a1dutch**
Add snoop to list of aggregators

### CODE REVIEW

**Comment by Gdewilde** [comment]
Thanks for your contribution. Can you provide us a link to the API aggregation service of Snoop? Is this available for developers?

**Comment by a1dutch** [comment]
https://snoop.app - it's just a consumer of openbanking api's rather than providing its own api's.

**Comment by Gdewilde** [comment]
Aha, we don't list those yet.

**Comment by a1dutch** [comment]
no worries i seen yolt and never realised they offer developer api's too

**Pull request closed without merging**
